server:
  port: ${PORT:8081}
spring:
  devtools:
    livereload:
      enable: true
  datasource:
    hikari:
      connection_timeout: 10000
      maximum_pool_size: 5
    url: jdbc:postgresql://ec2-3-211-245-154.compute-1.amazonaws.com:5432/d4hbek2q5g902q?sslmode=require&user=erbrapclajlnhu&password=c5b8d8203c3b7c8ee7dcc5f5de3035c967d094a1f9ca033f5dac733977bfb98a
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      jdbc:
        non_contextual_creation: true

